'use client'
import React from "react";
import { Swiper, SwiperSlide } from 'swiper/react';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
// import required modules
import { Pagination, Navigation } from 'swiper/modules';

import { FeaturedItem } from "./featured-item";
import SwiperCommon from "./swiper-common";

const FeaturedPrompts = () => {
    const items = [
        {
            type: "🎨 DALL·E",
            image: "/images/intro1.webp",
            info: "Whimsical Gnomes In Hilarious Situations",
            price: "$3.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/intro2.webp",
            info: "Playful Line Doodles generated by midjourney",
            price: "$2.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/intro3.webp",
            info: "Folkloric Watercolor Illustrations generated by midjourney",
            price: "$4.99"
        },
        {
            type: "🤖 GPT",
            image: "/images/intro4.webp",
            info: "Perfect Your Prompts",
            price: "$1.99"
        },
        {
            type: "🎨 DALL·E",
            image: "/images/FeaturedPrompts/5.webp",
            info: "Whimsical Gnomes In Hilarious Situations",
            price: "$4.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/FeaturedPrompts/6.webp",
            info: "Playful Line Doodles generated by midjourney",
            price: "$3.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/FeaturedPrompts/7.webp",
            info: "Folkloric Watercolor Illustrations generated by midjourney",
            price: "$3.99"
        },
        {
            type: "🤖 GPT",
            image: "/images/FeaturedPrompts/8.webp",
            info: "Perfect Your Prompts",
            price: "$2.99"
        },
        {
            type: "🎨 DALL·E",
            image: "/images/FeaturedPrompts/9.webp",
            info: "Whimsical Gnomes In Hilarious Situations",
            price: "$1.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/FeaturedPrompts/10.webp",
            info: "Playful Line Doodles generated by midjourney",
            price: "$1.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/FeaturedPrompts/11.webp",
            info: "Folkloric Watercolor Illustrations generated by midjourney",
            price: "$3.99"
        },
        {
            type: "🤖 GPT",
            image: "/images/FeaturedPrompts/12.webp",
            info: "Perfect Your Prompts",
            price: "$3.99"
        },
        {
            type: "🎨 DALL·E",
            image: "/images/FeaturedPrompts/13.webp",
            info: "Whimsical Gnomes In Hilarious Situations",
            price: "$3.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/FeaturedPrompts/14.webp",
            info: "Playful Line Doodles generated by midjourney",
            price: "$3.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/FeaturedPrompts/15.webp",
            info: "Folkloric Watercolor Illustrations generated by midjourney",
            price: "$3.99"
        },
        {
            type: "🤖 GPT",
            image: "/images/FeaturedPrompts/16.webp",
            info: "Perfect Your Prompts",
            price: "$3.99"
        },

    ]

    return (
        <div>
            <SwiperCommon items={items} mainTitle="Featured Prompts" />
        </div>
    );
};

export default FeaturedPrompts;