'use client'
import React from "react";
import { Swiper, SwiperSlide } from 'swiper/react';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
// import required modules
import { Pagination, Navigation } from 'swiper/modules';

import { FeaturedItem } from "./featured-item";
import SwiperCommon from "./swiper-common";

const HottestPrompts = () => {
    const items = [
        {
            type: "🎨 DALL·E",
            image: "/images/hottestprompts/1.webp",
            info: "Whimsical Gnomes In Hilarious Situations",
            price: "$2.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/hottestprompts/2.webp",
            info: "Playful Line Doodles generated by midjourney",
            price: "$2.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/hottestprompts/3.webp",
            info: "Folkloric Watercolor Illustrations generated by midjourney",
            price: "$1.99"
        },
        {
            type: "🤖 GPT",
            image: "/images/hottestprompts/4.webp",
            info: "Perfect Your Prompts",
            price: "$1.99"
        },
        {
            type: "🎨 DALL·E",
            image: "/images/hottestprompts/5.webp",
            info: "Whimsical Gnomes In Hilarious Situations",
            price: "$3.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/hottestprompts/6.webp",
            info: "Playful Line Doodles generated by midjourney",
            price: "$3.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/hottestprompts/7.webp",
            info: "Folkloric Watercolor Illustrations generated by midjourney",
            price: "$5.99"
        },
        {
            type: "🤖 GPT",
            image: "/images/hottestprompts/8.webp",
            info: "Perfect Your Prompts",
            price: "$5.99"
        },
        {
            type: "🎨 DALL·E",
            image: "/images/hottestprompts/9.webp",
            info: "Whimsical Gnomes In Hilarious Situations",
            price: "$2.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/hottestprompts/10.webp",
            info: "Playful Line Doodles generated by midjourney",
            price: "$2.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/hottestprompts/11.webp",
            info: "Folkloric Watercolor Illustrations generated by midjourney",
            price: "$3.99"
        },
        {
            type: "🤖 GPT",
            image: "/images/hottestprompts/12.webp",
            info: "Perfect Your Prompts",
            price: "$3.99"
        },
        {
            type: "🎨 DALL·E",
            image: "/images/hottestprompts/13.webp",
            info: "Whimsical Gnomes In Hilarious Situations",
            price: "$1.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/hottestprompts/14.webp",
            info: "Playful Line Doodles generated by midjourney",
            price: "$1.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/hottestprompts/15.webp",
            info: "Folkloric Watercolor Illustrations generated by midjourney",
            price: "$1.99"
        },
        {
            type: "🤖 GPT",
            image: "/images/hottestprompts/16.webp",
            info: "Perfect Your Prompts",
            price: "$3.99"
        },

    ]
    return (
        <div>
            <SwiperCommon items={items} mainTitle="Hottest Prompts" />

        </div>
    );
};

export default HottestPrompts;