'use client'
import React from "react";
import { Swiper, SwiperSlide } from 'swiper/react';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
// import required modules
import { Pagination, Navigation } from 'swiper/modules';

import { FeaturedItem } from "./featured-item";
import SwiperCommon from "./swiper-common";

const PopularWeek = () => {
    const items = [
        {
            type: "🎨 DALL·E",
            image: "/images/intro1.webp",
            info: "Whimsical Gnomes In Hilarious Situations",
            price: "$2.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/intro2.webp",
            info: "Playful Line Doodles generated by midjourney",
            price: "$2.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/intro3.webp",
            info: "Folkloric Watercolor Illustrations generated by midjourney",
            price: "$3.99"
        },
        {
            type: "🌌 Stable Diff.",
            image: "/images/stable/9.webp",
            info: "Fancy Feathers",
            price: "$1.99"
        },
        {
            type: "🎨 DALL·E",
            image: "/images/intro1.webp",
            info: "Whimsical Gnomes In Hilarious Situations",
            price: "$2.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/intro2.webp",
            info: "Playful Line Doodles generated by midjourney",
            price: "$2.99"
        },
        {
            type: "🌌 Stable Diff.",
            image: "/images/stable/14.webp",
            info: "Crystal Flower Figurine",
            price: "$3.99"
        },
        {
            type: "🤖 GPT",
            image: "/images/intro4.webp",
            info: "Perfect Your Prompts",
            price: "$3.99"
        },
        {
            type: "🎨 DALL·E",
            image: "/images/intro1.webp",
            info: "Whimsical Gnomes In Hilarious Situations",
            price: "$4.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/intro2.webp",
            info: "Playful Line Doodles generated by midjourney",
            price: "$4.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/intro3.webp",
            info: "Folkloric Watercolor Illustrations generated by midjourney",
            price: "$3.99"
        },
        {
            type: "🤖 GPT",
            image: "/images/intro4.webp",
            info: "Perfect Your Prompts",
            price: "$3.99"
        },
        {
            type: "🎨 DALL·E",
            image: "/images/intro1.webp",
            info: "Whimsical Gnomes In Hilarious Situations",
            price: "$2.99"
        },
        {
            type: "🎨 DALL·E",
            image: "/images/dalle/13.webp",
            info: "Christmas Greeting Cards Illustrations",
            price: "$2.99"
        },
        {
            type: "⛵ Midjourney",
            image: "/images/intro3.webp",
            info: "Folkloric Watercolor Illustrations generated by midjourney",
            price: "$1.99"
        },
        {
            type: "🤖 GPT",
            image: "/images/intro4.webp",
            info: "Perfect Your Prompts",
            price: "$1.99"
        },

    ]
    return (
        <div>
            <SwiperCommon items={items} mainTitle="Popular Week" />
        </div>
    );
}
export default PopularWeek;